### ISSUE TITLE
question: enhance to work with csv field?

### ISSUE THREAD

**Issue by mi-hol** [FriedrichWeinmann/ResolveString#2]
Hi Friedrich,

a common requirement for Extract Transform Load (ETL) scenarios is to replace an input field value with a different output value based on a defined rule.

I've searched PowerGallery and github for modules that would support this requirement but was unsuccessful.

Could this module be enhanced to replace strings for csv files and defined fields inside?

**Comment by FriedrichWeinmann** [comment]
Hello mi-hol,

in a way it already can do that:
You can register replacement values using `Register-StringMapping`. This can be a static string value _or a scriptblock_ .

With that set up, it's just a matter of running this through a pipeline:

```powershell
Import-Csv .\source.csv | ForEach-Object {
    $_.Property1 = $_.Property1 | Resolve-String
    $_
} | Export-Csv .\destination.csv
```

It would certainly possible to wrap this into a helper function and it to the module, but it seemed to specific a use-case for me to implement (I _do_ accept pull requests :-) ).

Cheers,
Fred

**Comment by mi-hol** [comment]
agreed a 'global' replace is currently feasible.
But what about a field specific replace for the use case: 'same source value in 2 fields, but only replace value for one of them'?

**Comment by FriedrichWeinmann** [comment]
You'll need to specify what you mean with "field" in this case.
What my snippet does is replace only one column in a csv table ("Property1"), rather than all entries...

**Comment by mi-hol** [comment]
my example code below doesn't replace yet :(
```
$sampleData = @'
Name,Date,Description
John,11/15/2016,This is a test
Matt,11/10/2016,This is also a test
Jim,2/30/2015,Third test
'@ | ConvertFrom-Csv

$csv_out_file = ".\SourceSample_Out.csv"
$CSVfieldDelimiter = ","

Write-Output "### sampleData"
$sampleData  

Write-Output "### sampleData member"
$sampleData  | Get-Member

# Replace "Matt" with "Matthew" in Name column
Register-StringMapping -Name 'Matt' -Value 'Matthew'

Write-Output "### Loop through each row of the CSV"
$sampleData | ForEach-Object {
    $_.Name = $_.Name | Resolve-String
    $_
} | Export-Csv $csv_out_file -NoTypeInformation

cat $csv_out_file
```

**Comment by FriedrichWeinmann** [comment]
Yeah, it does not, because the string mappings are bound by module name (sorry, kind of forgot about that one).
If you run it outside of a module, it automatically assigns the ModuleName `<Unknown>`, but for some reasons I don't automatically select for that right now. I may want to update that.

Anyway, to make your example work, update the line where you call `Resolve-String`:

```powershell
$_.Name = $_.Name | Resolve-String -ModuleName '<Unknown>'
```

**Comment by mi-hol** [comment]
Thank you so much, works perfectly!
I choose a different approach to assign module names

```
$sampleData = @'
Name,Date,Description
John,11/15/2016,This is a test
Matt,11/10/2016,This is also tested
Jim,2/30/2015,Tested test
'@ | ConvertFrom-Csv

$csv_out_file = ".\SourceSample_Out.csv"
$CSVfieldDelimiter = ","

Write-Output "### sampleData"
$sampleData  

Write-Output "### sampleData member"
$sampleData  | Get-Member

# Replace "Matt" with "Matthew" in Name column
Register-StringMapping -Name 'Matt' -Value 'Matthew' -ModuleName ReplName
# Replace "test" with "TEST" in Description column
# todo: convert to scriptblock that replaces only when the full word matches!!
Register-StringMapping -Name 'test' -Value 'TEST' -ModuleName ReplDescription

Write-Output "### Loop through each row of the CSV"
$sampleData | ForEach-Object {
    $_.Name = $_.Name | Resolve-String -ModuleName ReplName
    $_.Description = $_.Description | Resolve-String -ModuleName ReplDescription
    $_
} | Export-Csv $csv_out_file -NoTypeInformation

cat $csv_out_file
```

maybe you'd have a hint for the remaining todo below?
```
# Replace "test" with "TEST" in Description column
# todo: convert to scriptblock that replaces only when the full word matches!!
Register-StringMapping -Name 'test' -Value 'TEST' -ModuleName ReplDescription
```

**Comment by mi-hol** [comment]
the example in readme is very brief, hence I lack understanding on: how to reference the 'source' field in the scriptblock?

I want to replace 'hardcoded' logic like below 
```
        $Environment = $row.Environment -Replace("Staging","Integration") `
                                        -Replace("Test - Lab","Test") `
                                        -Replace("Test - Certification","Test") 
```

**Comment by FriedrichWeinmann** [comment]
Heya, alright, let's take a look:

> convert to scriptblock that replaces only when the full word matches

This is currently not supported (sorry).
I'm open to adding it as an option though. I can tell you it's a low priority for me (I don't have a use-case where I need that), but am more than willing to accept PRs to that effect.

> I choose a different approach to assign module names

The modulename thing is really to make it seamlessly work when consumed by another module. The commands will automatically pick up the module the caller belongs to and pick the correct mapping. That way, multiple modules will not interfere with each other by accident, if both register mappings.
You are free to define as many of them as you feel the need to, just be aware that each `Resolve-String` call can only have a single modulename.

> I want to replace 'hardcoded' logic like below

Like this?

```powershell
# Registered once
Register-StringMapping -Name 'Staging' -Value 'Integration' -ModuleName MyWorkflow
Register-StringMapping -Name 'Test - Lab' -Value 'Test' -ModuleName MyWorkflow
Register-StringMapping -Name 'Test - Certification' -Value 'Test' -ModuleName MyWorkflow
```

Then execute:
```powershell
$Environment = $row.Environment | Resolve-String -ModuleName MyWorkflow
```

If it all happens from commands within the same module, that could be shortened to:

```powershell
# Registered once
Register-StringMapping -Name 'Staging' -Value 'Integration'
Register-StringMapping -Name 'Test - Lab' -Value 'Test'
Register-StringMapping -Name 'Test - Certification' -Value 'Test'
```

Then execute:
```powershell
$Environment = $row.Environment | Resolve-String
```
